---
abstract: 'Adds over 24:00:00 methods to Time::Piece'
author:
  - 'Syunsuke Fujishiro'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Time-Piece-Over24
no_index:
  directory:
    - inc
    - t
requires:
  Time::Piece: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.010
